### ISSUE TITLE
AwsCommonRuntimeKit.cleanUp() hangs after calling Auth APIs (signUp)

### ISSUE THREAD

**Issue by thisisabhash** [awslabs/aws-crt-swift#134]
### Describe the bug

GraphQL IAM requests need to be SigV4 signed, so APIPlugin will call AwsCommonRuntimeKit.initialize() on configure() and then AwsCommonRuntimeKit.cleanUp() on `reset()`. 
The code hangs on aws_auth_library_clean_up -> aws_http_library_clean_up -> aws_thread_join_all_managed -> line 113

```
aws_condition_variable_wait_pred(
                &s_managed_thread_signal, &s_managed_thread_lock, s_one_or_fewer_managed_threads_unjoined, NULL);
```
https://github.com/awslabs/aws-c-common/blob/main/source/thread_shared.c#L67

We see integration tests at 
https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginGraphQLIAMTests/GraphQLWithIAMIntegrationTests.swift 
run indefinitely. 
If we comment out `.cleanUp()` in 
https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin%2BResettable.swift,
the test runs successfully.

This only happens after Auth APIs are called (signUp)

Auth.fetchAuthSession, check if isSignedIn, AwsCommonRuntimeKit.cleanUp() - ✅
Auth.signUp, AwsCommonRuntimeKit.cleanUp() - ❌

More info here : https://github.com/aws-amplify/amplify-swift/issues/2120

### Expected Behavior

AwsCommonRuntimeKit.cleanUp() should not hang

### Current Behavior

AwsCommonRuntimeKit.cleanUp() hangs

### Reproduction Steps

Integration test here : 
https://github.com/aws-amplify/amplify-swift/blob/158bcb3de48bcd569ff5ee2babdad6bbeed25430/AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginGraphQLIAMTests/GraphQLWithIAMIntegrationTests.swift#L60

### AWS CRT SWIFT version used

0.3.1

### Compiler and Version used

AWSSwiftSDK 0.5.0, Xcode Version 14.0 (14A309), Swift version 5.7

### Operating System and version

macOS 12.6.2

**Comment by waahm7** [comment]
AwsCommonRuntime.cleanUp() awaits all threads to join to ensure everything is cleaned up. If there are any Swift object keeping a reference to CRT resources like HostResolver, it will keep waiting for it to release so that it can finish the clean-up. Cleanup is an opt-in feature if someone wants to make sure everything gets cleaned up and there aren’t any memory leaks at the end of application.

I am looking more to find out if there are any CRT resources that are preventing clean-up in reset. I would suggest updating latest version of crt-swift as we have fixed a lot of memory leaks and reference cycles which might also be causing an issue.

**Comment by thisisabhash** [comment]
Just a quick update - still seeing this issue after updating to Swift SDK 0.6.0 with CRT version 0.4.0.

**Comment by waahm7** [comment]
@thisisabhash Hi,

I have updated the [docs](https://github.com/awslabs/aws-crt-swift/blob/ccec2f72be237d79c4ddc1a14ea5355bd36e5a91/Source/AwsCommonRuntimeKit/CommonRuntimeKit.swift#L29) to explain the cleanup behavior. It is an optional feature to make sure that there are no resources alive at the end. It is expected to hang if there is any resource still holding reference to CRT resource. You do not need to call cleanup normally and the Swift SDK never calls cleanup.

**Comment by thisisabhash** [comment]
Thank you for the confirmation. Will remove the call to this optional feature.
